dist: bionic

language: python
python:
  - "3.6"
  
branchs:
only:
    - master
    
before install:
  - export FLASK_APP=app.py

install:
  - pip install flask
  - pip install tox
  - pip install tox-travis
script:
  - python -m flask run && tox
